### ISSUE TITLE
Choose a permissive licence

### ISSUE THREAD

**Issue by gcharest** [cds-snc/technical-playbook-manuel-technique#2]
Great work on the playbook! I just wanted to point out that this should be the default when possible.

Depending on the tech stack and architecture choices, you may be required to choose a less permissive licence for compliance purposes.

Which also goes into the automated testing: dependencies licence compliance can be highly automated so that should most likely be part of your project setup.

Thanks! :+1:

**Comment by wmoussa-cds** [comment]
Thanks Guillaume for your feedback and suggestion. I think that make sense. I was expecting such nuances to be raised. I'm just not sure yet if we should just clarify the skill description or add some extra notes in a reference section. What do you think?

**Comment by gcharest** [comment]
Probably at least a few notes with regards to compliance: in a Dev team, it does mean being able to know all your dependencies. If you choose a licence, it must abide by the choices you took in terms of development.

[Heather Meeker's](https://www.goodreads.com/book/show/35046386-open-source-for-business#other_reviews) examples are usually a good way to visualize what we should be thinking of when putting software out there (whether it's OSS or not):

![image](https://user-images.githubusercontent.com/1690085/107256864-0a4c7e80-6a08-11eb-975d-684279bdb0ba.png)
